# Generated by Django 4.1.1 on 2023-03-01 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=10, unique=True, verbose_name='手機號碼')),
                ('password', models.CharField(max_length=32)),
                ('username', models.CharField(max_length=11, verbose_name='用戶名')),
                ('email', models.EmailField(max_length=254)),
                ('is_active', models.BooleanField(default=False, verbose_name='是否驗證')),
                ('date_of_birth', models.DateField()),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_user_profile',
            },
        ),
    ]
