# Generated by Django 4.1.1 on 2023-04-14 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='商品類別')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '商品類別',
                'verbose_name_plural': '商品類別',
                'db_table': 'goods_catalog',
            },
        ),
        migrations.CreateModel(
            name='SaleAttrValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='銷售屬性值')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '銷售屬性值',
                'verbose_name_plural': '銷售屬性值',
                'db_table': 'goods_sale_attr_value',
            },
        ),
        migrations.CreateModel(
            name='SKU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='SKU名稱')),
                ('caption', models.CharField(max_length=100, verbose_name='副標題')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='單價')),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='成本價')),
                ('market_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='市場價')),
                ('stock', models.IntegerField(default=0, verbose_name='庫存')),
                ('sales', models.IntegerField(default=0, verbose_name='銷量')),
                ('comments', models.IntegerField(default=0, verbose_name='評價數')),
                ('is_launched', models.BooleanField(default=True, verbose_name='是否上架銷售')),
                ('default_image_url', models.ImageField(default=None, upload_to='sku', verbose_name='默認圖片')),
                ('version', models.IntegerField(default=0, verbose_name='庫存版本')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('sale_attr_value', models.ManyToManyField(to='goods.saleattrvalue')),
            ],
            options={
                'verbose_name': 'SKU表',
                'verbose_name_plural': 'SKU表',
                'db_table': 'goods_sku',
            },
        ),
        migrations.CreateModel(
            name='SPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名稱')),
                ('sales', models.IntegerField(default=0, verbose_name='商品銷量')),
                ('comments', models.IntegerField(default=0, verbose_name='評價數量')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.catalog', verbose_name='商品類別')),
            ],
            options={
                'verbose_name': 'SPU',
                'verbose_name_plural': 'SPU',
                'db_table': 'goods_spu',
            },
        ),
        migrations.CreateModel(
            name='SPUSpec',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='SPU規格名稱')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('spu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.spu')),
            ],
            options={
                'verbose_name': 'SPU規格',
                'verbose_name_plural': 'SPU規格',
                'db_table': 'goods_spu_spec',
            },
        ),
        migrations.CreateModel(
            name='SPUSaleAttr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='SPU屬性名稱')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('spu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.spu')),
            ],
            options={
                'verbose_name': 'SPU銷售屬性',
                'verbose_name_plural': 'SPU銷售屬性',
                'db_table': 'goods_spu_sale_attr',
            },
        ),
        migrations.CreateModel(
            name='SKUSpecValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='SKU規格名稱值')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.sku')),
                ('spu_spec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.spuspec')),
            ],
            options={
                'verbose_name': 'SKU規格屬性表',
                'verbose_name_plural': 'SKU規格屬性表',
                'db_table': 'goods_spu_spec_value',
            },
        ),
        migrations.CreateModel(
            name='SKUImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='sku_images', verbose_name='圖片路徑')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.sku', verbose_name='sku')),
            ],
            options={
                'verbose_name': 'SKU圖片',
                'verbose_name_plural': 'SKU圖片',
                'db_table': 'goods_sku_image',
            },
        ),
        migrations.AddField(
            model_name='sku',
            name='spu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.spu'),
        ),
        migrations.AddField(
            model_name='saleattrvalue',
            name='spu_sale_attr',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.spusaleattr', verbose_name='銷售屬性'),
        ),
    ]
