# Generated by Django 4.1.1 on 2023-05-08 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0005_address'),
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('order_id', models.CharField(max_length=64, primary_key=True, serialize=False, verbose_name='訂單編號')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='訂單總金額')),
                ('total_count', models.IntegerField(verbose_name='商品總數')),
                ('pay_method', models.SmallIntegerField(default=1, verbose_name='支付方式')),
                ('freight', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='運費')),
                ('status', models.SmallIntegerField(choices=[(1, '待付款'), (2, '待出貨'), (3, '待收穫'), (4, '訂單完成')], verbose_name='訂單狀態')),
                ('receiver', models.CharField(max_length=10, verbose_name='收件人')),
                ('address', models.CharField(max_length=100, verbose_name='收件地址')),
                ('receiver_mobile', models.CharField(max_length=11, verbose_name='手機')),
                ('tag', models.CharField(max_length=10, verbose_name='標籤')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('user_profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile')),
            ],
            options={
                'db_table': 'orders_order_info',
            },
        ),
        migrations.CreateModel(
            name='OrderGoods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1, verbose_name='數量')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='單價')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('order_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.orderinfo')),
                ('sku', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='goods.sku')),
            ],
            options={
                'db_table': 'orders_order_goods',
            },
        ),
    ]
