# Generated by Django 4.1.1 on 2023-07-01 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='status',
            field=models.SmallIntegerField(choices=[(1, '待付款'), (2, '待出貨'), (3, '待收貨'), (4, '訂單完成')], verbose_name='訂單狀態'),
        ),
    ]
